# the user model specifies its fields (or columns) declaratively
# import the BaseModel class to define it
    # Within the basemodel script we have a Settings object which specifies the database
from peewee import *
import os
import sys
import inspect
# currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
# parentdir = os.path.dirname(currentdir)
# print(currentdir)
# print(parentdir)

from .BaseModel import BaseModel

#Model class that defines each column that represents a statistic
class PlayerGeneralTraditionalPerGamePositions(BaseModel):
    season_id = CharField(null=True)
    PLAYER_ID  = IntegerField(null=True)
    PLAYER_NAME = CharField(null=True)
    player_position = CharField(null=True)
    NICKNAME = CharField(null=True)
    TEAM_ID  = IntegerField(null=True)
    TEAM_ABBREVIATION = CharField(null=True)
    AGE = IntegerField(null=True)
    GP = IntegerField(null=True)
    W = IntegerField(null=True)
    L = IntegerField(null=True)
    W_PCT = FloatField(null=True)
    MIN = FloatField(null=True)
    FGM = FloatField(null=True)
    FGA = FloatField(null=True)
    FG_PCT = FloatField(null=True)
    FG3M = FloatField(null=True)
    FG3A = FloatField(null=True)
    FG3_PCT = FloatField(null=True)
    FTM = FloatField(null=True)
    FTA = FloatField(null=True)
    FT_PCT = FloatField(null=True)
    OREB = FloatField(null=True)
    DREB = FloatField(null=True)
    REB = FloatField(null=True)
    AST = FloatField(null=True)
    TOV = FloatField(null=True)
    STL = FloatField(null=True)
    BLK = FloatField(null=True)
    BLKA = FloatField(null=True)
    PF = FloatField(null=True)
    PFD = FloatField(null=True)
    PTS = FloatField(null=True)
    PLUS_MINUS = FloatField(null=True)
    NBA_FANTASY_PTS = FloatField(null=True)
    DD2 = FloatField(null=True)
    TD3 = FloatField(null=True)
    WNBA_FANTASY_PTS = FloatField(null=True)
    GP_RANK = IntegerField(null=True)
    W_RANK = IntegerField(null=True)
    L_RANK = IntegerField(null=True)
    W_PCT_RANK = IntegerField(null=True)
    MIN_RANK = IntegerField(null=True)
    FGM_RANK = IntegerField(null=True)
    FGA_RANK = IntegerField(null=True)
    FG_PCT_RANK = IntegerField(null=True)
    FG3M_RANK = IntegerField(null=True)
    FG3A_RANK = IntegerField(null=True)
    FG3_PCT_RANK = IntegerField(null=True)
    FTM_RANK = IntegerField(null=True)
    FTA_RANK = IntegerField(null=True)
    FT_PCT_RANK = IntegerField(null=True)
    OREB_RANK = IntegerField(null=True)
    DREB_RANK = IntegerField(null=True)
    REB_RANK = IntegerField(null=True)
    AST_RANK = IntegerField(null=True)
    TOV_RANK = IntegerField(null=True)
    STL_RANK = IntegerField(null=True)
    BLK_RANK = IntegerField(null=True)
    BLKA_RANK = IntegerField(null=True)
    PF_RANK = IntegerField(null=True)
    PFD_RANK = IntegerField(null=True)
    PTS_RANK = IntegerField(null=True)
    PLUS_MINUS_RANK = IntegerField(null=True)
    NBA_FANTASY_PTS_RANK = IntegerField(null=True)
    DD2_RANK = IntegerField(null=True)
    TD3_RANK = IntegerField(null=True)
    WNBA_FANTASY_PTS_RANK = IntegerField(null=True)
    CFID = IntegerField(null=True)
    CFPARAMS = CharField(null=True)
    # data is coming from nba_sql.db
    class Meta:
       db_table = 'player_general_traditional_pergame_positions'